---
- name: Run all of the roles
  hosts: localhost
  connection: local
  vars_files:
    - .secrets/vars.yml
  roles:
    - role: git
      tags: [ git ]
    - role: dotfiles
      tags: [ dotfiles ]
    - role: zsh
      tags: [ zsh ]
    - role: home-bin
      tags: [ home-bin ]
    - role: python
      tags: [ python ]
    - role: gnupg
      tags: [ gnupg ]
    - role: pass
      tags: [ pass ]
