---

roles:
  - name: build_tools
    src: https://github.com/mtik00/ansible-role-build-tools.git
  - name: pyenv
    src: https://github.com/mtik00/ansible-role-pyenv.git

collections:
  - name: community.general
