---

roles:
  - name: build_tools
    src: https://github.com/mtik00/ansible-role-build-tools.git
  - name: pyenv
    src: https://github.com/mtik00/ansible-role-pyenv.git
  - name: aws_cli
    src: https://github.com/mtik00/ansible-role-aws-cli.git
  - name: gnupg
    src: https://github.com/mtik00/ansible-role-gnupg.git
  - name: docker
    src: https://github.com/mtik00/ansible-role-docker.git
  - name: tmux
    src: https://github.com/mtik00/ansible-role-tmux.git

collections:
  - name: community.general
