---
- name: Configure work-specific items
  hosts: localhost
  connection: local
  vars_files:
    - .secrets/vars.yml
  vars:
    env_d_mode: '0770'
    env_files_path: "{{ ansible_user_dir }}/.env-files.d"
    apt_cache_valid_time: 600
    gnupg_default_cache_ttl: 28800  # 8 hours

    configure_insomnia: false  # only enable outside of WSL
    configure_scaleft: true
    configure_vault: true
    configure_zoom: false  # only enable outside of WSL
    configure_zscaler: true
    configure_aws_cli: true

  tasks:
    - name: Install common apt packages
      become: true
      ansible.builtin.apt:
        state: present
        cache_valid_time: "{{ apt_cache_valid_time }}"
        name:
          - curl
          - pass
          - pass-extension-otp
          - ripgrep

  roles:
    - role: mtik00.build_tools
      tags: [build_tools]

    - role: mtik00.git
      tags: [git]

    - role: mtik00.dotfiles
      tags: [dotfiles]

    - role: mtik00.zsh
      tags: [zsh]

    - role: mtik00.home_bin
      tags: [home_bin]

    - role: mtik00.home_folders
      tags: [home_folders]
      vars:
        additional_folders:
          - name: gp
            mode: '0770'

    - role: mtik00.pyenv
      tags: [pyenv]

    - role: mtik00.gnupg
      tags: [gnupg]

    - role: mtik00.docker
      tags: [docker]

    - role: mtik00.tmux
      tags: [tmux]

    - role: mtik00.one_password
      tags: [one_password]

    - role: mtik00.zscaler
      tags: [zscaler]

    - role: zoom
      tags: [zoom]

    - role: vault
      tags: [vault]

    - role: scaleft
      tags: [scaleft]

    - role: mtik00.saml2aws
      tags: [saml2aws]

    - role: insomnia
      tags: [insomnia]

    - role: aws_cli
      tags: [aws_cli]
