---
- name: dotfiles folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.dotfiles"
    state: directory
    mode: 0755

- name: copy dotfiles
  ansible.builtin.copy:
    src: files/.dotfiles
    dest: "{{ ansible_user_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0655

- name: Create symbolic link for .direnvrc
  ansible.builtin.file:
   src: "{{ ansible_user_dir }}/.dotfiles/.direnvrc"
   dest: "{{ ansible_user_dir }}/.direnvrc"
   force: yes
   state: link

- name: vimrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.vimrc"
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    create: yes
    block: |
      set spell spelllang=en_us
      hi clear SpellBad
      hi SpellBad cterm=underline,bold ctermfg=red
      if has("autocmd")
        au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
      endif
      set number
      set ignorecase
      set smartcase

- name: copy fonts
  ansible.builtin.copy:
    src: files/.fonts
    dest: "{{ ansible_user_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0655"

- name: Create symbolic link for .desk
  ansible.builtin.file:
   src: "{{ ansible_user_dir }}/.dotfiles/.desk"
   dest: "{{ ansible_user_dir }}/.desk"
   force: yes
   state: link

- name: env-files.d folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.env-files.d"
    state: directory
    mode: "{{ env_d_mode }}"
