---

- name: Check for pip
  shell: which pip
  register: pip_check
  failed_when: no
  no_log: yes
  changed_when: false

- name: Check for pip3
  shell: which pip3
  register: pip3_check
  failed_when: no
  no_log: yes
  changed_when: false

- name: Download pip bootstrap
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    force: yes
    mode: '0777'
  when: (pip_check is failed) or (pip3_check is failed)

- name: Install pip
  command: python get-pip.py --user
  args:
    chdir: /tmp
  when: (pip_check is failed)

- name: Install pip3
  command: python3 get-pip.py --user
  args:
    chdir: /tmp
  when: (pip3_check is failed)

- name: Clean up
  file:
    path: /tmp/get-pip.py
    state: absent
  when: (pip_check is failed) or (pip3_check is failed)
