- name: Install pyenv
  shell: curl https://pyenv.run | bash
  args:
    creates: "{{ ansible_user_dir }}/.pyenv/"
    warn: false
  register: pyenv_installed

# This is a workaround for `git pull` always seeing a change.
# pyenv.run does some things, as well as pulling down the git repo.  Updating
# pyenv is as simple as updating the clone.  Hopefully the install script
# doesn't change this.
- name: Update pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_user_dir }}/.pyenv/"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Python dependency packages
  ansible.builtin.apt:
    name:
    - build-essential
    - curl
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - llvm
    - make
    - python-openssl
    - tk-dev
    - wget
    - xz-utils
    - zlib1g-dev
  when: pyenv_installed is changed

- name: Pyenv Python versions
  ansible.builtin.command: "{{ ansible_user_dir }}/.pyenv/bin/pyenv install {{ item }}"
  args:
    creates: "{{ ansible_user_dir }}/.pyenv/versions/{{ item }}/"
  loop:
    - "{{ python_version }}"

- name: Default python version file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.python-version"
    content: "{{ python_version }}"

- name: pyenv .zprofile setup
  ansible.builtin.blockinfile:
    marker: "# {mark} PYENV -- ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_user_dir }}/.zprofile"
    insertafter: EOF
    create: yes
    block: |
      export PYENV_ROOT="{{ ansible_user_dir }}/.pyenv"
      eval "$({{ ansible_user_dir }}/.pyenv/bin/pyenv init -)"
      export PATH="{{ ansible_user_dir }}/.pyenv/bin:$PATH"
      export PATH=$(pyenv root)/shims:$PATH

- name: pyenv .profile setup
  blockinfile:
    marker: "# {mark} PYENV -- ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_user_dir }}/.profile"
    insertafter: EOF
    create: yes
    block: |
      export PYENV_ROOT="{{ ansible_user_dir }}/.pyenv"
      eval "$({{ ansible_user_dir }}/.pyenv/bin/pyenv init -)"
      export PATH="{{ ansible_user_dir }}/.pyenv/bin:$PATH"
      export PATH=$(pyenv root)/shims:$PATH
