---

- ansible.builtin.assert:
    that:
      - env_files_path

- name: Install gnupg package
  become: yes
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name:
      - gpg
    state: present

- name: Ensure gnupg director exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory
    mode: '0700'

- name: Configure gpg
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    mode: "0600"
    content: |
      use-agent

- name: Configure gpg agent
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    mode: "0600"
    content: |
      default-cache-ttl {{ default_cache_ttl }}
      max-cache-ttl {{ max_cache_ttl }}

- name: Add GPG TTY
  ansible.builtin.lineinfile:
    path: "{{ env_files_path }}/gnupg"
    line: export GPG_TTY=$(tty)
    create: yes
