---

- name: fonts
  import_tasks: fonts.yml

- name: Install zsh package(s)
  become: yes
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name:
      - zsh
    state: present

- name: Install oh-my-zsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh/lib/"
    warn: false
  become: no

- name: make zsh default
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: zshrc
  import_tasks: zshrc.yml

- name: powerlevel9k
  import_tasks: powerlevel9k.yml

- name: zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/puginz/zsh-autosuggestions"

- name: Make sure env-files.d is last
  ansible.builtin.blockinfile:
    insertbefore: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- env-files.d"
    path: "{{ ansible_user_dir }}/.zshrc"
    block: |
      # Source all files in the env-files.d directory ###############################
      for f in {{ ansible_user_dir }}/.env-files.d/*; do
          source "${f}"
      done
      ###############################################################################
