---

- name: git PPA repo
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    codename: "{{ ansible_lsb.codename }}"
    state: present

- name: git package
  ansible.builtin.apt:
    name: git
    state: latest
