---

- name: facts
  import_tasks: facts.yml

- name: Add 1password repo
  become: yes
  block:
    - name: 1password | get the key
      ansible.builtin.shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output {{ one_password_gpg_key }}
      args:
        creates: "{{ one_password_gpg_key }}"

    - name: 1password | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ dpkg_arch }} signed-by={{ one_password_gpg_key }}] https://downloads.1password.com/linux/debian/{{ dpkg_arch }} stable main"
        update_cache: yes
        state: present

- name: Install 1password package
  become: yes
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name:
      - 1password-cli
    state: present
