---

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"
    name:
      - apt-transport-https
      - aptitude
      - ca-certificates
      - curl

# NOTE: This is a bit sketchy and untested.  I can't figure out why the community
# version of update-alternatives constantly failed, so there's this.  Also,
# this only appears to be needed in WSL, not regular Ubuntu.
- name: Get stats of the iptables link
  ansible.builtin.stat:
    path: /etc/alternatives/iptables
  register: iptables_symlink

- name: update alternatives
  become: true
  ansible.builtin.command: update-alternatives --set iptables /usr/sbin/iptables-legacy
  when:
    - lookup('env','WSL_DISTRO_NAME') != ""
    - iptables_symlink.stat.islnk is not defined or iptables_symlink.stat.lnk_target != "/usr/sbin/iptables-legacy"

- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Update apt and install docker-ce
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: docker-ce
    state: present

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - docker
