---

- name: Check installed version
  ansible.builtin.shell:
    cmd: |
      if [[ -f {{ ansible_user_dir }}/bin/saml2aws ]]; then
        {{ ansible_user_dir }}/bin/saml2aws --version 2>&1
      else
        echo "0"
      fi
    executable: /bin/bash
  register: installed_version
  changed_when: false

- name: Get latest saml2aws version  # noqa command-instead-of-module
  ansible.builtin.shell: |
      set -o pipefail && curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1
  args:
    executable: /bin/bash
  register: saml2aws_version
  changed_when: false

- name: latest version
  ansible.builtin.debug:
    msg: "Latest saml2aws version: '{{ saml2aws_version.stdout }}'\nInstalled saml2aws version: '{{ installed_version.stdout }}'"

- name: install saml2aws  # noqa command-instead-of-module
  ansible.builtin.shell: |
      set -o pipefail && wget -qc https://github.com/Versent/saml2aws/releases/download/v{{ saml2aws_version.stdout }}/saml2aws_{{ saml2aws_version.stdout }}_linux_amd64.tar.gz -O - | tar -xzv -C {{ ansible_user_dir }}/bin
      chmod u+x {{ ansible_user_dir }}/bin/saml2aws --version
  args:
    executable: /bin/bash
  when: installed_version.stdout is version(saml2aws_version.stdout, '<')
  become: true
